matrix:
  include:
    - language: python
      python:
        - "2.7"
      install:
        - pip install -r ./src/requirements.txt
      script: nosetests
    - language: node_js
      node_js:
        - 'stable'
        - 'lts/*'
      script:
        - npm test